/*
 * 389. Find the Difference
 * two string s & t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t
 */
 
#include <stdio.h>

#define LETTERS_NUM 26

char findTheDifference(char *s, char* t) {
	int letters[LETTERS_NUM] = {0,};
	while(*s) {
		letters[*s-97]++;
		s++;
	}
	while(*t) {
		letters[*t-97]--;
		t++;
	}


	int i=0;
	for(i = 0; i < 26; i++) {
		if(letters[i] < 0)
			return i + 97;
	}
	printf("\n");
	return 0;
}



int main() {

	char c = findTheDifference("aaabcd", "abaacde");
	if(c > 0) {
		printf("'%c' is the letter that was added.\n", c);
	}
	return 0;
 }
